services:
    rf.cellulr.generator_command:
        class: Rf\CellulR\GeneratorBundle\Command\GenerateWebComponentCommand
        arguments:
            - '%kernel.root_dir%'
            - ''
        tags:
            -  { name: console.command }